name       : haskell-constraints
version    : '0.10'
release    : 2
source     :
    - https://hackage.haskell.org/package/constraints-0.10/constraints-0.10.tar.gz : c224b82e53c21791083c83fed2f2c938bd715a63c8efa90a5abcc3d8859126c6
license    : BSD-2-Clause
component  : programming.haskell
summary    : GHC 7.4 gave us the ability to talk about ConstraintKinds. They stopped crashing the compiler in GHC 7.6.
description: "GHC 7.4 gave us the ability to talk about ConstraintKinds. They stopped crashing the compiler in GHC 7.6. \n"
builddeps  :
    - haskell-cabal-install
    - haskell-hashable
    - haskell-mtl
    - haskell-semigroups
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |-
    %cabal_install
    %cabal_register
