name       : haskell-constraints
version    : '0.12'
release    : 3
source     :
    - https://hackage.haskell.org/package/constraints-0.12/constraints-0.12.tar.gz : f26b531a15f013f15b4b5df46c4f89b13927253a4195494c50320adf05760223
license    : BSD-2-Clause
component  : programming.haskell
summary    : GHC 7.4 gave us the ability to talk about ConstraintKinds. They stopped crashing the compiler in GHC 7.6.
description: |
    GHC 7.4 gave us the ability to talk about ConstraintKinds. They stopped crashing the compiler in GHC 7.6.
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-semigroups-devel
    - haskell-transformers-compat-devel
    - haskell-type-equality-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
        - haskell-semigroups-devel
        - haskell-transformers-compat-devel
        - haskell-type-equality-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
