name       : haskell-constraints
version    : 0.9
release    : 1
source     :
    - http://hackage.haskell.org/package/constraints-0.9/constraints-0.9.tar.gz : b7b4135ceacdd18d291bbd83277cc21bbb066d0e16ce35f879619f17c1c8d29d
license    : BSD-2-Clause
component  : programming.haskell
summary    : GHC 7.4 gave us the ability to talk about ConstraintKinds. They stopped crashing the compiler in GHC 7.6. 
description: |
    GHC 7.4 gave us the ability to talk about ConstraintKinds. They stopped crashing the compiler in GHC 7.6. 
builddeps  :
    - haskell-cabal-install
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register